# Generated by Django 3.2.4 on 2024-04-25 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0002_vote_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityproblem',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='city_problems', to='auth.user'),
            preserve_default=False,
        ),
    ]
