# Generated by Django 3.2.4 on 2024-04-25 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0003_cityproblem_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.AlterModelOptions(
            name='cityproblem',
            options={'verbose_name': 'Проблема города', 'verbose_name_plural': 'Проблемы города'},
        ),
        migrations.AlterModelOptions(
            name='finalist',
            options={'verbose_name': 'Финалист', 'verbose_name_plural': 'Финалисты'},
        ),
        migrations.AlterModelOptions(
            name='solutionproposal',
            options={'verbose_name': 'Предложение решения', 'verbose_name_plural': 'Предложения решений'},
        ),
        migrations.AlterModelOptions(
            name='vote',
            options={'verbose_name': 'Голос', 'verbose_name_plural': 'Голоса'},
        ),
        migrations.AlterField(
            model_name='cityproblem',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_problems', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='cityproblem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='cityproblem',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='cityproblem',
            name='location',
            field=models.CharField(blank=True, max_length=255, verbose_name='Местоположение'),
        ),
        migrations.AlterField(
            model_name='cityproblem',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='cityproblem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='finalist',
            name='solution',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finalist_status', to='forum.solutionproposal', verbose_name='Решение'),
        ),
        migrations.AlterField(
            model_name='finalist',
            name='votes_in_final',
            field=models.IntegerField(default=0, verbose_name='Голоса в финале'),
        ),
        migrations.AlterField(
            model_name='solutionproposal',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to=settings.AUTH_USER_MODEL, verbose_name='Автор решения'),
        ),
        migrations.AlterField(
            model_name='solutionproposal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='solutionproposal',
            name='description',
            field=models.TextField(verbose_name='Описание решения'),
        ),
        migrations.AlterField(
            model_name='solutionproposal',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='forum.cityproblem', verbose_name='Проблема'),
        ),
        migrations.AlterField(
            model_name='solutionproposal',
            name='votes',
            field=models.IntegerField(default=0, verbose_name='Голоса'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата голосования'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='solution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_set', to='forum.solutionproposal', verbose_name='Решение'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='value',
            field=models.IntegerField(default=1, verbose_name='Значение голоса'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL, verbose_name='Голосующий'),
        ),
        migrations.AddField(
            model_name='cityproblem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.category', verbose_name='Категория'),
        ),
    ]
