# Generated by Django 3.2.4 on 2024-04-25 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_answer_poll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityproblem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city_problems', to='forum.category', verbose_name='Категория'),
        ),
    ]
