# Generated by Django 3.2.4 on 2024-05-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_auto_20240514_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityproblem',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Необходимая сумма'),
        ),
    ]
