# Generated by Django 3.2.4 on 2024-05-14 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_cityproblem_total_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('city_problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='forum.cityproblem')),
            ],
            options={
                'verbose_name': 'Инвестор',
                'verbose_name_plural': 'Инвесторы',
            },
        ),
    ]
